### ISSUE TITLE
那个SDK包我咋在VS2017上配置不完整呀，哭了

### ISSUE THREAD

**Issue by Houhongqiu** [AngelMonica126/GraphicAlgorithm#10]

**Comment by AngelMonica126** [comment]
缺少那个呢？或者说是第几个项目跑步起来，报的什么错误？

**Comment by Houhongqiu** [comment]
我按照你给的配置说明，那个项目中的FRAME框架生成的动态链接库我不知道怎么操作，还有就是那个SDK堡中的环境变量设置好后，需不需要把里面的每个开源包的库和库目录都单独在在VS2017上配置好呀，求大佬指点指点，呜呜呜



> 缺少那个呢？或者说是第几个项目跑步起来，报的什么错误？

我按照你给的配置说明，那个项目中的FRAME框架生成的动态链接库我不知道怎么操作，还有就是那个SDK堡中的环境变量设置好后，需不需要把里面的每个开源包的库和库目录都单独在在VS2017上配置好呀，求大佬指点指点，呜呜呜

**Comment by AngelMonica126** [comment]
点击Frame，右键，生成即可

**Comment by Houhongqiu** [comment]
> 点击Frame，右键，生成即可

那SDK里的那些包如何在VS2017上配置好呢？需要一个一个的把库和路径配置上去吗

**Comment by Houhongqiu** [comment]
> > 点击Frame，右键，生成即可
> 
> 那SDK里的那些包如何在VS2017上配置好呢？需要一个一个的把库和路径配置上去吗

大佬还在不，呜呜呜

**Comment by AngelMonica126** [comment]
跟着步骤来就好

**Comment by Houhongqiu** [comment]
是用VS打开项目后，点击ＦＲＡＭＥ生成自动连接库，然后就直接跑代码吗，呜呜呜

**Comment by Houhongqiu** [comment]
是用VS打开项目后，点击ＦＲＡＭＥ生成自动连接库，然后就直接跑代码吗，呜呜呜





> 跟着步骤来就好

是用VS打开项目后，点击ＦＲＡＭＥ生成自动连接库，然后就直接跑代码吗，呜呜呜
